README.md
defaults/main.yml
tasks/clean/remove_domain.yml

On a DR cleanup scenario all storage domains are moved to maintenance
and detached from the DC.
Part of those storage domains might run tasks and could not be moved to
maintenance.
In that case the clean process should wait and try to move the SD to
maintenance after a delay.
To overcome that usecase two default attributes were added to configure
the retry and delay properties to support the cleanup.
Bug-Url: https://bugzilla.redhat.com/1533427

Add retry and delay properties to support setup cleanup

---

library/ovirt_storage_domains.py

Port recent changes from https://github.com/ansible/ansible/pull/34904:
Add missing storage domain properties:
Add additional attributes on adding/import storage domain to oVirt.
The properties are :
wipe_after_delete - Boolean flag which indicates whether the storage domain should wipe the data after delete.
backup - Boolean flag which indicates whether the storage domain is configured as backup or not.
critical_space_action_blocker - Indicates what is the minimum free space the storage domain should contain.
warning_low_space - Indicates the minimum percentage of a free space in a storage domain to present a warning.

port additional properties patch from ansible to DR

---

tasks/recover/add_domain.yml

This patch adds a proper error message when no hosts
are available instead of the "list object has no element 0"
message and stop the importing of storage domains for the
DC.
Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>

Add a proper error message when no hosts available

---

README.md
defaults/main.yml

target site should have default value of secondary since most of the
time the fail-over process should be done to the secondary site and not
the primary site

Change default value for target host and source mapping

---

tasks/generate_mapping.py
tasks/recover_engine.yml

Add the ability for the user to define a storage domain which will be master
in the primary setup and not master in secondary setup.

master storage domain should be configured for each setup

---

README.md
defaults/main.yml
tasks/clean/remove_domain.yml
tasks/clean/remove_domain_process.yml
tasks/clean/remove_filtered_master_domains.yml
tasks/clean/shutdown_vm.yml
tasks/clean/shutdown_vms.yml
tasks/clean/update_ovf_store.yml
tasks/clean_engine.yml

Fix for the following bugs:
BZ1533427 - retry remove storage domains only for active storage domains
BZ1533385 - Add the ability to clean only mapped storage domains.
Support the ability to clean only mapped storage domains by using the
following actions only for the mapped storage domains:
a) shutdown VMs which are only related mapped SDs
b) Update OVF_STORE disks for active mapped SDs
c) cleanup storage domains which are mapped
This patch follow the same concept of clean setup as before:
The flow of remove storage domains is defined in a way that is
applied seperatly to master storage domains and non-master storage domains.
the flow should be as follow:
a) Remove active non-master storage domains
b) Force remove inactive non-master storage domains
c) Remove active master storage domains …

BZ1533385 - Add the ability to clean only mapped storage domains.

---

tasks/run_unregistered_entities.yml

The relative path of run_vms should be under /tasks/recover instead of
/tasks

Fix relative path for unregistered_vms on failback

---

tasks/recover/print_info.yml

Make the entity report available in stdout not only
in verbose mode.
Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>

Print the entity report to stdout

---

automation/README.md

Current link gives 404 error. Updated it with ovirt-infra-docs.readthedocs.io documentation page.

Update link for Build and test standards

---

files/dr.conf
files/fail_back.py
files/fail_over.py
tasks/clean/remove_filtered_master_domains.yml
tasks/clean/shutdown_vm.yml
tasks/clean/shutdown_vms.yml
tasks/clean/update_ovf_store.yml
tasks/clean_engine.yml
tasks/main.yml
tasks/recover/add_domain.yml
tasks/recover/print_info.yml
tasks/recover/register_template.yml
tasks/recover/register_templates.yml
tasks/recover/register_vm.yml
tasks/recover/register_vms.yml
tasks/recover/run_vms.yml
tasks/recover_engine.yml
tasks/run_unregistered_entities.yml

1) Use report log in the tmp folder instead of files since we print this
already as part failover and failback scripts
2) Change deprecated succeeded/failed conditions
3) Set missing names for tasks with missing names

Fixes related to report.log and task names

---

files/fail_back.py
files/fail_over.py
files/generate_vars.py
files/validator.py

1) Use VaultLib instead of Vault to reduce package dependecy
2) Use SafeConfigParser from ConfigParser

Avoid missing dependencies when running ovirt-dr

---

files/generate_mapping.py
files/validator.py
tasks/clean/remove_invalid_filtered_master_domains.yml
tasks/clean/remove_valid_filtered_master_domains.yml
tasks/clean_engine.yml

The engine clean process fetch the storage domain which is about
to be removed from oVirt using searchQuery.
This fetch operation does not support query with parentheses, therefore
to overcome that obligation each condition in the 'or' clause must also
include the storage domain name.
Also adding validation to avoid export storage domain in mapping var file

Bz1576553 -  Use query suffix for clean setup in fail back

---

README.md
callback_plugins/stdout.py
files/dr.conf
files/fail_back.py
files/fail_over.py
files/generate_vars.py
files/ovirt-dr
files/validator.py
files/vault_secret.sh
tasks/clean_engine.yml
tasks/recover/add_domain.yml

1. Changes in vault and Configparse usages to avoid any missing dependecies in RHEL installation.
2. dr-play.yml will be copied to "files" folder to be used for the ovirt-dr script.
3. Introduce the use of log file in ovirt-dr script.
The script default location and level is configured in the dr.conf
Default location is /var/log/ovirt-dr/ovirt-dr.log and default level is "DEBUG"
The user can override it with --log-file and --log-level
If no log file will be specified stdout will be used to print the output.

Support log for ansible-disaster-recovery

---

files/ovirt-dr

The validate operation is intuitive to the user and using log file is
redundant.
The following patch should filter out the log from the validate
operation.
Bug-Url: https://bugzilla.redhat.com/1588465

log file should not be part of validate

---

README.md
defaults/main.yml
files/fail_back.py
files/validator.py
tasks/clean/remove_domain_process.yml
tasks/clean/remove_valid_filtered_master_domains.yml
tasks/clean/shutdown_vms.yml
tasks/recover_engine.yml
tasks/run_unregistered_entities.yml
tasks/unregister_entities.yml

Preserve the VMs statuses in a seperate file instead in the memory, so in case the failback operation will fail in the middle the admin will still have the information about the VMs that ran before on the secondary site

Support unregistered entities in file

---

build.sh
ovirt-ansible-disaster-recovery.spec.in

Version 112 should include the following fixes:
rhbz#1533404 - Support unregistered entities in file
rhbz#1589535 - Support validation for previewed VMs and delete protected VMs
Additional minor fixes

New release 1.1.2

---

ovirt-ansible-disaster-recovery.spec.in

Fixes RPM build errors:
bogus date in %changelog: Thu Oct 31 2018 Maor Lipchuk <mlipchuk@redhat.com> - 1.1.3-1
bogus date in %changelog: Thu Sep 12 2018 Maor Lipchuk <mlipchuk@redhat.com> - 1.1.2-1

packaging: spec: fix bogus dates

---

files/fail_back.py
files/fail_over.py
files/generate_vars.py
files/ovirt-dr
files/validator.py

Using "ConfigParser" instead of the deprecated (since Python 3.2)
"SafeConfigParser" to fix warnings like the following one:
./ovirt-dr:114: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.

python, warnings: Eliminate usages of the deprecated DeprecationWarning

---

tox.ini

This fixes the ansible-lint tests.
I have added the `-x 106` to ignore the wrong name of the role/repository.

Fix ansible_lint tox test

---

tasks/recover/print_info.yml
tasks/recover_engine.yml
tasks/run_unregistered_entities.yml
tasks/unregister_entities.yml

Fixing the following errors:
[207] Nested jinja pattern
[208] File permissions not mentioned
[305] Use shell only when shell functionality is required

CI, tox: fixing CI errors produced by ansible_lint

---

tasks/clean/remove_domain_process.yml
tasks/clean/remove_invalid_filtered_master_domains.yml
tasks/clean/remove_valid_filtered_master_domains.yml
tasks/clean/shutdown_vms.yml
tasks/clean_engine.yml
tasks/recover/add_domain.yml
tasks/recover/print_info.yml
tasks/recover/register_templates.yml
tasks/recover/register_vms.yml
tasks/recover_engine.yml
tasks/run_unregistered_entities.yml

1) Updating "include:" & "include_tasks:" paths to be relative to the location
of the relevant yaml files (vs. relative to the project root).
2) Typo fixed.

CI, tox: fixing CI warnings produced by ansible_lint

---

files/validator.py

Usage of the plain "yaml.load(input)" is deprecated since PyYAML 5.1.
Fixing the following type of PyYAML warnings:
/home/pbar/dev/git/ovirt-ansible-disaster-recovery/files/validator.py:108: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
info_dict = yaml.load(info)

PyYAML: fixing "yaml.load()" deprecation warnings

---

README.md
meta/main.yml
ovirt-ansible-disaster-recovery.spec.in
tasks/clean/remove_domain_process.yml
tasks/clean/remove_invalid_filtered_master_domains.yml
tasks/clean/remove_valid_filtered_master_domains.yml
tasks/clean/shutdown_vms.yml
tasks/clean/update_ovf_store.yml
tasks/clean_engine.yml
tasks/recover/add_domain.yml
tasks/recover/add_fcp_domain.yml
tasks/recover/add_glusterfs_domain.yml
tasks/recover/add_iscsi_domain.yml
tasks/recover/add_nfs_domain.yml
tasks/recover/add_posixfs_domain.yml
tasks/recover/register_templates.yml
tasks/recover/register_vms.yml
tasks/recover_engine.yml
tasks/unregister_entities.yml

Fixing deprecation warnings produced by tox & Ansible due to upgrading to Ansible 2.9:
1) ovirt_vm_facts --> ovirt_vm_info
2) ovirt_host_facts -->ovirt_host_info
3) ovirt_disk_facts --> ovirt_disk_info
4) ovirt_storage_vm_facts --> ovirt_storage_vm_info
5) ovirt_storage_template_facts --> ovirt_storage_template_info
6) ovirt_storage_domain_facts --> ovirt_storage_domain_info
Requirements documentation:
1) Updating the requirements to use Ansible 2.9.
2) Other improvements & fixes.

Ansible 2.9: fixing deprecation warnings

---

files/fail_back.py
files/fail_over.py

- Fixing code warnings.
- Local variables' renaming to improve readability, fixing confusing/bad names.
- Different code reorganizations to improve readability.
- Updating "enter vault password" to make failover to be consistent with failback flow.
- Fixing log message that prints a wrong setup (target instead of source):
"Starting failback DR from setup XXX"
- Adding "TODO"s to be handled later.

python, warnings: Multiple code improvements in "fail_over.py" & "fail_back.py"

---

files/generate_mapping.py
ovirt-ansible-disaster-recovery.spec.in

Some fixes I didn't want to lose prior to moving to collections.
1) Fixing small typos in "ovirt-ansible-disaster-recovery.spec.in".
2) Minor code style improvements in "generate_mapping.py".

spec, python: small issues fixed

---

files/generate_vars.py
files/validator.py

Solving a few issues to enhance moving to collections:
1. Removing unused path variable in "generate_vars.py" containing the "disaster-recovery" substring (that otherwise should have been changed in the collections project).
2. Fixing a bug with user input in "validator.py".
3. A few improvements in "validator.py"

pre-collections: small issues fixed
